import mongoose from 'mongoose';
import { v4 as uuidv4 } from 'uuid';

const questionSchema = new mongoose.Schema({
  id: { type: String, default: () => uuidv4() }, // Unique ID for each question
  questionText: { type: String, required: true },
  type: { type: String, enum: ['MCQ', 'ShortAnswer'], required: true },
  options: [String], // For MCQ type
  answer: { type: String, required: true },
  points: { type: Number, default: 1 }, // Points for this question
  resources: [String] // Array of resource links
});

const quizSchema = new mongoose.Schema({
  title: { type: String, required: true },
  description: { type: String },
  subjectId: { type: mongoose.Schema.Types.ObjectId, ref: 'Subject', required: true },
  questions: [questionSchema],
  timeLimit: { type: Number, default: null }, // Time limit in seconds (null = no limit)
  shuffleQuestions: { type: Boolean, default: false }, // Whether to shuffle questions for each attempt
  isAIGenerated: { type: Boolean, default: false }, // Whether quiz was generated by AI
  createdBy: { type: mongoose.Schema.Types.ObjectId, ref: 'User' }, // User who created the quiz
  isPublic: { type: Boolean, default: false }, // Whether quiz is visible to all users
  difficulty: { type: String, enum: ['easy', 'medium', 'hard'], default: 'medium' },
  year: { type: String, enum: ['All', '1', '2', '3', '4', '5'], default: 'All' },
  passingScore: { type: Number, default: 70 } // Percentage required to pass
}, {
  timestamps: true
});

export default mongoose.model('Quiz', quizSchema);

